import {test,expect} from '@playwright/test';
test('Rust diagnostics, source selection and example loading',async({page})=>{await page.goto('/PROOF/');await expect(page.locator('#status')).toContainText('Rust checked');await page.selectOption('#example','broken');await page.click('#load');await expect(page.locator('.diagnostic').first()).toBeVisible();await expect(page.locator('#diagnostics')).toContainText('md_h1_count');await page.locator('.diagnostic').first().click();expect(await page.locator('#source').evaluate(e=>e.selectionEnd>e.selectionStart)).toBe(true);});
test('math, fenced source and source sharing',async({page})=>{await page.goto('/PROOF/?example=math');await expect(page.locator('#status')).toContainText('Rust checked');await page.selectOption('#view','terminal');await expect(page.locator('#terminal')).toContainText('α + β = γ');await expect(page.locator('#terminal')).toContainText('$\\alpha$ stays literal');await page.click('#share');await page.reload();await expect(page.locator('#source')).toHaveValue(/Terminal math/);await expect(page.locator('#status')).toContainText('Rust checked');});
test('bounds disable generated exports and source download preserves input',async({page})=>{await page.goto('/PROOF/');await expect(page.locator('#markdown')).toBeEnabled();const input='# Download\n\nOriginal source.\n';await page.fill('#source',input);await expect(page.locator('#markdown')).toBeEnabled();const [download]=await Promise.all([page.waitForEvent('download'),page.click('#markdown')]);const stream=await download.createReadStream();let content='';for await(const chunk of stream)content+=chunk.toString();expect(content).toBe(input);await page.fill('#source','x'.repeat(65537));await expect(page.locator('#status')).toContainText('64KB');await expect(page.locator('#markdown')).toBeEnabled();await expect(page.locator('#html')).toBeDisabled();});
test('preview is sandboxed, unsafe HTML escaped and mobile fits',async({page})=>{await page.goto('/PROOF/');await expect(page.locator('#status')).toContainText('Rust checked');await page.fill('#source','# Safe\n<script>parent.document.title="pwned"</script>\n![remote](https://example.org/track.png)');await expect(page.locator('#status')).toContainText('Rust checked');await expect(page.locator('#preview')).toHaveAttribute('sandbox','');await expect(page.frameLocator('#preview').locator('body')).toContainText('<script>');await expect(page).toHaveTitle('PROOF · Markdown workbench');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});

test('worker failure remains actionable after editing',async({page})=>{await page.route('**/*.wasm',route=>route.abort());await page.goto('/PROOF/');await expect(page.locator('#status')).toContainText('unavailable');await page.fill('#source','# Keep editing');await expect(page.locator('#status')).toContainText('unavailable');await expect(page.locator('#html')).toBeDisabled();});
test('footnote links retain the preview document',async({page})=>{await page.goto('/PROOF/');await expect(page.locator('#status')).toContainText('Rust checked');await page.fill('#source','# Notes\n\nHello[^note].\n\n[^note]: Footnote definition.');const frame=page.frameLocator('#preview');await expect(frame.locator('h1')).toHaveText('Notes');await frame.locator('a[href="#note"]').first().click();await expect(frame.locator('h1')).toHaveText('Notes');await expect(frame.locator('#note')).toContainText('Footnote definition');});

test('retired preview URLs are released after delayed replacements',async({page})=>{
 await page.addInitScript(()=>{window.previewURLs=[];window.revokedURLs=[];window.holdPreview=false;const create=URL.createObjectURL.bind(URL);const revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);window.previewURLs.push(url);return url;};URL.revokeObjectURL=url=>{window.revokedURLs.push(url);revoke(url);};const descriptor=Object.getOwnPropertyDescriptor(HTMLIFrameElement.prototype,'src');window.releasePreview=()=>{window.holdPreview=false;descriptor.set.call(document.getElementById('preview'),window.pendingPreview);};Object.defineProperty(HTMLIFrameElement.prototype,'src',{get:descriptor.get,set(value){if(window.holdPreview){window.pendingPreview=value;}else descriptor.set.call(this,value);}});});
 await page.goto('/PROOF/');await expect(page.frameLocator('#preview').locator('h1')).toHaveText('Field notes');await page.evaluate(()=>window.holdPreview=true);
 for(const title of ['Alpha','Beta','Gamma']){const count=await page.evaluate(()=>window.previewURLs.length);await page.fill('#source','# '+title);await expect.poll(()=>page.evaluate(()=>window.previewURLs.length)).toBe(count+1);}
 await page.evaluate(()=>window.releasePreview());await expect(page.frameLocator('#preview').locator('h1')).toHaveText('Gamma');await expect.poll(()=>page.evaluate(()=>window.previewURLs.slice(0,-1).every(url=>window.revokedURLs.includes(url)))).toBe(true);expect(await page.evaluate(()=>window.revokedURLs.includes(window.previewURLs.at(-1)))).toBe(false);
});
