use clap::{Parser, Subcommand};
use std::path::PathBuf;

use crate::cmd_context::GlobalOptions;

#[derive(Parser)]
#[command(
    name = "proof",
    version,
    about = "A fast, schema-driven markdown and ASCII art linter with AI-assisted fix pipeline",
    long_about = None,
)]
pub(crate) struct Cli {
    #[command(subcommand)]
    command: Option<Command>,

    /// Files or directories to lint (default: current directory)
    paths: Vec<PathBuf>,

    /// Schema config file (default: proof.toml in target directory)
    #[arg(short, long, global = true)]
    config: Option<PathBuf>,

    /// Output format: text (default) | json | rich | github
    #[arg(short = 'f', long, default_value = "text", global = true)]
    format: String,

    /// Show only errors (suppress warnings)
    #[arg(short = 'e', long, global = true)]
    errors_only: bool,

    /// Exit with code 0 even if issues found
    #[arg(long, global = true)]
    no_fail: bool,

    /// Write output to file instead of stdout
    #[arg(short = 'o', long, global = true)]
    output: Option<PathBuf>,
}

pub(crate) struct DispatchInput {
    command: Option<Command>,
    top_level_paths: Vec<PathBuf>,
    globals: GlobalOptions,
}

impl Cli {
    pub(crate) fn into_dispatch(self) -> DispatchInput {
        let Cli {
            command,
            paths,
            config,
            format,
            errors_only,
            no_fail,
            output,
        } = self;

        let globals = GlobalOptions::new(config, format, errors_only, no_fail, output);

        DispatchInput {
            command,
            top_level_paths: paths,
            globals,
        }
    }
}

impl DispatchInput {
    pub(crate) fn take_command(&mut self) -> Option<Command> {
        self.command.take()
    }

    pub(crate) fn take_top_level_paths(&mut self) -> Vec<PathBuf> {
        std::mem::take(&mut self.top_level_paths)
    }

    pub(crate) fn take_globals(self) -> GlobalOptions {
        self.globals
    }
}

#[derive(Subcommand)]
pub(crate) enum Command {
    /// Generate source candidates from existing markdown artifacts
    Backfill(crate::cmd_backfill::Args),
    /// Lint files and report diagnostics (default)
    Check(crate::cmd_check::Args),
    /// Apply a fix plan generated by AI
    Fix(crate::cmd_fix::Args),
    /// Generate a pre-populated draft fix plan — AI fills in decisions inline
    Draft(crate::cmd_draft::Args),
    /// Pin a figure as a DaVinci — registers it in proof.toml with invariants
    Pin(crate::cmd_pin::Args),
    /// List all pinned DaVinci figures
    PinList,
    /// Resolve an md:// URI — print the element content, label, and line range
    Resolve(crate::cmd_resolve::Args),
    /// List every .source.md file referencing an md:// URI (reverse dependency lookup).
    /// File-only and heading-only queries match all references at or below that scope.
    Depends(crate::cmd_depends::Args),
    /// Print the effective config for a path
    Config(crate::cmd_config::Args),
    /// Delegate corpus-intelligence workflows to MDCROP
    Mdcrop(crate::cmd_mdcrop::Args),
    /// Generate a corpus index page
    Index(crate::cmd_index::Args),
    /// Generate a corpus table-of-contents page
    Toc(crate::cmd_index::Args),
    /// Generate a corpus catalog page with metadata and link side-info
    Catalog(crate::cmd_index::Args),
    /// Write a proof.toml to the current directory
    Init,
    /// Corpus health summary — source count, stale files, last compile time
    Status(crate::cmd_status::Args),
    /// Summary statistics (error/warning counts by directory and code)
    Stats(crate::cmd_stats::Args),
    /// Compile source documents — resolve proof: directives and write output
    Compile(crate::cmd_compile::Args),
    /// Generate or validate ASCII tree diagrams
    Tree(crate::cmd_tree::Args),
    /// Analyze a figure and generate suggested DaVinci invariants
    SpecGenerate(crate::cmd_spec_generate::Args),
    /// Compose N figures side-by-side into a single ASCII art collage
    Layout(crate::cmd_layout::Args),
}
