use crate::diagnostic::Severity;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DiagnosticCode {
    pub code: &'static str,
    pub default_severity: Severity,
    pub family: &'static str,
    pub description: &'static str,
}

pub const DIAGNOSTIC_CODES: &[DiagnosticCode] = &[
    DiagnosticCode {
        code: "ascii_arrow_gap",
        default_severity: Severity::Warning,
        family: "ascii_flow",
        description: "Gap inside a horizontal arrow body.",
    },
    DiagnosticCode {
        code: "ascii_barchart_align",
        default_severity: Severity::Warning,
        family: "ascii_barchart",
        description: "Bar chart value columns are not aligned.",
    },
    DiagnosticCode {
        code: "ascii_barchart_char",
        default_severity: Severity::Warning,
        family: "ascii_barchart",
        description: "Bar chart rows use inconsistent bar characters.",
    },
    DiagnosticCode {
        code: "ascii_barchart_pad",
        default_severity: Severity::Warning,
        family: "ascii_barchart",
        description: "Bar chart label/bar or bar/value padding is below policy.",
    },
    DiagnosticCode {
        code: "ascii_barchart_scale",
        default_severity: Severity::Warning,
        family: "ascii_barchart",
        description: "Bar width is disproportionate to its numeric value.",
    },
    DiagnosticCode {
        code: "ascii_barchart_value",
        default_severity: Severity::Warning,
        family: "ascii_barchart",
        description: "Bar chart value formats differ across rows.",
    },
    DiagnosticCode {
        code: "ascii_box_col",
        default_severity: Severity::Error,
        family: "ascii_box",
        description: "Box content or border columns do not align with expected junctions.",
    },
    DiagnosticCode {
        code: "ascii_box_width",
        default_severity: Severity::Error,
        family: "ascii_box",
        description: "A box row has a different visual width than its opening border.",
    },
    DiagnosticCode {
        code: "ascii_cell_padding",
        default_severity: Severity::Warning,
        family: "ascii_flow",
        description: "Cell content is flush against a real box delimiter when padding can fit.",
    },
    DiagnosticCode {
        code: "ascii_char_range",
        default_severity: Severity::Warning,
        family: "ascii_char",
        description: "Code-block character is outside the configured alignment-safe ranges.",
    },
    DiagnosticCode {
        code: "ascii_connector_drift",
        default_severity: Severity::Warning,
        family: "ascii_flow",
        description: "Vertical connector columns drift between connector-only lines.",
    },
    DiagnosticCode {
        code: "ascii_table_candidate",
        default_severity: Severity::Warning,
        family: "backfill",
        description: "Backfill inventory detected an ASCII table candidate block.",
    },
    DiagnosticCode {
        code: "ascii_unclosed_fence",
        default_severity: Severity::Warning,
        family: "ascii_box",
        description: "A fenced code block was opened but not closed.",
    },
    DiagnosticCode {
        code: "CHART-001",
        default_severity: Severity::Error,
        family: "chart",
        description: "Chart rendering failed.",
    },
    DiagnosticCode {
        code: "CHART-002",
        default_severity: Severity::Error,
        family: "chart",
        description: "Chart directive source or data is invalid.",
    },
    DiagnosticCode {
        code: "COMPILE-001",
        default_severity: Severity::Error,
        family: "compile",
        description: "Locked DaVinci invariant violation during compile.",
    },
    DiagnosticCode {
        code: "COMPILE-002",
        default_severity: Severity::Error,
        family: "compile",
        description: "Compile directive could not be resolved or rendered.",
    },
    DiagnosticCode {
        code: "COMPILE-003",
        default_severity: Severity::Warning,
        family: "compile",
        description: "Warning-tier DaVinci invariant violation during compile.",
    },
    DiagnosticCode {
        code: "COMPILE-004",
        default_severity: Severity::Error,
        family: "compile",
        description: "Element row declaration is invalid.",
    },
    DiagnosticCode {
        code: "COMPILE-007",
        default_severity: Severity::Warning,
        family: "compile",
        description: "Embedded figure lint or missing DaVinci pin found during compile.",
    },
    DiagnosticCode {
        code: "DASHBOARD-001",
        default_severity: Severity::Error,
        family: "dashboard",
        description: "Dashboard region is outside the canvas bounds.",
    },
    DiagnosticCode {
        code: "DASHBOARD-002",
        default_severity: Severity::Error,
        family: "dashboard",
        description: "Dashboard region has invalid geometry.",
    },
    DiagnosticCode {
        code: "DASHBOARD-003",
        default_severity: Severity::Error,
        family: "dashboard",
        description: "Dashboard regions overlap.",
    },
    DiagnosticCode {
        code: "DASHBOARD-004",
        default_severity: Severity::Error,
        family: "dashboard",
        description: "Dashboard region reference is not declared.",
    },
    DiagnosticCode {
        code: "DASHBOARD-005",
        default_severity: Severity::Warning,
        family: "dashboard",
        description: "Dashboard content overflows its target region.",
    },
    DiagnosticCode {
        code: "DASHBOARD-006",
        default_severity: Severity::Warning,
        family: "dashboard",
        description: "Dashboard canvas exceeds the standard terminal width threshold.",
    },
    DiagnosticCode {
        code: "ELEMENT-001",
        default_severity: Severity::Error,
        family: "element",
        description: "Element directive is missing required data or has invalid dimensions.",
    },
    DiagnosticCode {
        code: "ELEMENT-002",
        default_severity: Severity::Error,
        family: "element",
        description: "Element field or row configuration is invalid.",
    },
    DiagnosticCode {
        code: "ELEMENT-003",
        default_severity: Severity::Error,
        family: "element",
        description: "Element source field cannot be read or parsed.",
    },
    DiagnosticCode {
        code: "ELEMENT-004",
        default_severity: Severity::Error,
        family: "element",
        description: "Element row width does not match the declared width.",
    },
    DiagnosticCode {
        code: "ELEMENT-005",
        default_severity: Severity::Error,
        family: "element",
        description: "Element source is missing or incompatible with the requested field.",
    },
    DiagnosticCode {
        code: "fig_invariant_violated",
        default_severity: Severity::Warning,
        family: "davinci",
        description: "Pinned figure invariant is not satisfied.",
    },
    DiagnosticCode {
        code: "FIGURE-001",
        default_severity: Severity::Error,
        family: "figure",
        description: "Figure rendering or shape declaration is invalid.",
    },
    DiagnosticCode {
        code: "FIGURE-003",
        default_severity: Severity::Error,
        family: "figure",
        description: "Figure dimensions or bounds are invalid.",
    },
    DiagnosticCode {
        code: "FIGURE-006",
        default_severity: Severity::Warning,
        family: "figure",
        description: "Figure rendering required clipping or lossy placement.",
    },
    DiagnosticCode {
        code: "io_error",
        default_severity: Severity::Error,
        family: "runner",
        description: "Input file could not be read.",
    },
    DiagnosticCode {
        code: "link_broken_target",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Relative Markdown link target does not exist.",
    },
    DiagnosticCode {
        code: "MATH-001",
        default_severity: Severity::Error,
        family: "math",
        description: "Math rendering failed or expression is invalid.",
    },
    DiagnosticCode {
        code: "MATH-003",
        default_severity: Severity::Warning,
        family: "math",
        description: "Math expression could not be rendered within the requested layout.",
    },
    DiagnosticCode {
        code: "MATH-004",
        default_severity: Severity::Warning,
        family: "math",
        description: "Rendered math was clipped to fit the target width.",
    },
    DiagnosticCode {
        code: "MATH-006",
        default_severity: Severity::Error,
        family: "math",
        description: "Math tokenizer found invalid or unmatched syntax.",
    },
    DiagnosticCode {
        code: "md_blockquote_spacing",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Block quote marker is missing the configured following space.",
    },
    DiagnosticCode {
        code: "md_break_style",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Thematic break style does not match project policy.",
    },
    DiagnosticCode {
        code: "md_broken_heading",
        default_severity: Severity::Warning,
        family: "source_links",
        description: "Source-link heading target does not exist.",
    },
    DiagnosticCode {
        code: "md_broken_link",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "Configured table link target does not exist.",
    },
    DiagnosticCode {
        code: "md_broken_uri",
        default_severity: Severity::Warning,
        family: "source_links",
        description: "Source-link md:// target cannot be resolved.",
    },
    DiagnosticCode {
        code: "md_duplicate_heading",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Duplicate heading text appears at the same heading level.",
    },
    DiagnosticCode {
        code: "md_empty_heading",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Heading marker has no heading text.",
    },
    DiagnosticCode {
        code: "custom_rule",
        default_severity: Severity::Warning,
        family: "custom_rules",
        description: "A configured custom rule matched its warn_when condition.",
    },
    DiagnosticCode {
        code: "custom_rule_invalid_regex",
        default_severity: Severity::Error,
        family: "custom_rules",
        description: "A configured custom rule regex could not compile.",
    },
    DiagnosticCode {
        code: "md_file_length",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "File exceeds the configured maximum line count.",
    },
    DiagnosticCode {
        code: "md_forbidden_section",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "A configured forbidden H2 heading appears.",
    },
    DiagnosticCode {
        code: "md_h1_count",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "File has more H1 headings than configured.",
    },
    DiagnosticCode {
        code: "md_heading_format",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Heading spacing or trailing hash style is invalid.",
    },
    DiagnosticCode {
        code: "md_heading_hierarchy",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "Heading levels skip one or more levels.",
    },
    DiagnosticCode {
        code: "md_numeric_uri_stale",
        default_severity: Severity::Warning,
        family: "source_links",
        description:
            "Numeric md:// URI selector is stale because a stable named selector is available.",
    },
    DiagnosticCode {
        code: "md_missing_pattern",
        default_severity: Severity::Error,
        family: "markdown",
        description: "A required content pattern is absent.",
    },
    DiagnosticCode {
        code: "md_missing_section",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "A required H2 heading is absent.",
    },
    DiagnosticCode {
        code: "md_missing_source",
        default_severity: Severity::Warning,
        family: "source_links",
        description: "A source document is missing required source-link declarations.",
    },
    DiagnosticCode {
        code: "md_missing_table",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "A required table is absent.",
    },
    DiagnosticCode {
        code: "md_table_cell_padding",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "GFM pipe table cell padding is below policy.",
    },
    DiagnosticCode {
        code: "md_table_col_mismatch",
        default_severity: Severity::Error,
        family: "markdown_table",
        description: "GFM pipe table row column counts differ.",
    },
    DiagnosticCode {
        code: "md_table_empty_header",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "GFM pipe table header cell is empty.",
    },
    DiagnosticCode {
        code: "md_table_missing_link",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "Configured link column contains bare text.",
    },
    DiagnosticCode {
        code: "md_table_schema",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "Configured table schema requirement is unmet.",
    },
    DiagnosticCode {
        code: "md_table_separator_invalid",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "GFM pipe table separator syntax is invalid.",
    },
    DiagnosticCode {
        code: "md_table_too_wide",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description: "GFM pipe table exceeds the configured maximum columns.",
    },
    DiagnosticCode {
        code: "source_inline_table",
        default_severity: Severity::Warning,
        family: "markdown_table",
        description:
            "A .source.md file contains an inline pipe table instead of normalized sidecar data.",
    },
    DiagnosticCode {
        code: "md_unexpected_section",
        default_severity: Severity::Warning,
        family: "markdown",
        description: "An H2 heading is outside the active closed-world allowlist.",
    },
    DiagnosticCode {
        code: "SLIDE-001",
        default_severity: Severity::Warning,
        family: "slide",
        description: "Slide exceeds the configured maximum bullet count.",
    },
    DiagnosticCode {
        code: "SLIDE-002",
        default_severity: Severity::Error,
        family: "slide",
        description: "Slide ratio or layout declaration is invalid.",
    },
    DiagnosticCode {
        code: "SLIDE-006",
        default_severity: Severity::Error,
        family: "slide",
        description: "Requested slide index is out of range.",
    },
    DiagnosticCode {
        code: "SLIDE-007",
        default_severity: Severity::Warning,
        family: "slide",
        description: "Slide bullet nesting exceeds the configured maximum depth.",
    },
    DiagnosticCode {
        code: "PPTX-001",
        default_severity: Severity::Error,
        family: "pptx",
        description: "PPTX target requires an explicit .slides.source.md source.",
    },
    DiagnosticCode {
        code: "PPTX-002",
        default_severity: Severity::Error,
        family: "pptx",
        description: "PPTX source could not be parsed into a native slide deck.",
    },
    DiagnosticCode {
        code: "SYMBOL-001",
        default_severity: Severity::Warning,
        family: "symbol",
        description: "Symbol token could not be resolved.",
    },
    DiagnosticCode {
        code: "SYMBOL-003",
        default_severity: Severity::Error,
        family: "symbol",
        description: "Shape symbol could not be resolved.",
    },
    DiagnosticCode {
        code: "TREE-001",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree connector ordering is invalid.",
    },
    DiagnosticCode {
        code: "TREE-002",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree continuation line alignment is invalid.",
    },
    DiagnosticCode {
        code: "TREE-003",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree indentation width is inconsistent.",
    },
    DiagnosticCode {
        code: "TREE-004",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree branch node has no child.",
    },
    DiagnosticCode {
        code: "TREE-005",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree root line has an invalid connector prefix.",
    },
    DiagnosticCode {
        code: "TREE-006",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree connector is not followed by exactly one label space.",
    },
    DiagnosticCode {
        code: "TREE-007",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree directory/file slash policy is violated.",
    },
    DiagnosticCode {
        code: "TREE-008",
        default_severity: Severity::Warning,
        family: "ascii_tree",
        description: "Tree entry path or duplicate-entry policy is violated.",
    },
    DiagnosticCode {
        code: "unused_figure",
        default_severity: Severity::Warning,
        family: "unused",
        description: "Markdown figure file is not referenced by any source document.",
    },
];

pub fn lookup(code: &str) -> Option<&'static DiagnosticCode> {
    DIAGNOSTIC_CODES.iter().find(|entry| entry.code == code)
}
