const $=id=>document.getElementById(id);
const examples={guide:'# Field notes\n\n## A small system\n\nKeep the source readable and the output useful.\n\n| Stage | Result |\n|-------|--------|\n| Draft | Markdown |\n| Check | Diagnostics |\n\n```text\n+----------+\n|  SOURCE  |\n+----------+\n```\n',broken:'# First title\n# Second title\n\n#### Skipped level\n\n| Name | Value |\n|------|-------|\n| One |\n\n```text\n+---------+\n| broken |\n+---------+\n```\n',math:'# Terminal math\n\n$\\alpha + \\beta = \\gamma$\n\n$\\sqrt{x} + x^2$\n\nInline math expands in the terminal view. HTML shows the original Markdown math text.\n\n```text\n$\\alpha$ stays literal in a fence.\n```\n'};
let id=0,result=null,ready=false,failed=false,previewURL=null;const retiredURLs=new Set();const downloads=['markdown','html','json'];
function invalidate(){id++;result=null;downloads.forEach(key=>$(key).disabled=true);$('diagnostics').replaceChildren();$('preview').hidden=true;$('terminal').textContent='';$('status').textContent=failed?'Rust engine unavailable. Reload to retry; your source is still editable.':ready?'Checking with Rust…':'Loading Rust engine…';}
function check(){invalidate();if(ready)worker.postMessage({id,source:$('source').value});}
const worker=new Worker('worker.js',{type:'module'});
worker.onerror=()=>{failed=true;ready=false;invalidate();$('status').textContent='Rust engine unavailable. Reload to retry; your source is still editable.';};
worker.onmessage=({data})=>{if(data.ready){ready=true;check();return;}if(data.id!==id)return;if(data.error){$('status').textContent=data.error;return;}result=data.result;downloads.forEach(key=>$(key).disabled=false);$('status').textContent=`Rust checked this document · ${result.diagnostics.length} diagnostic${result.diagnostics.length===1?'':'s'}`;if(!result.diagnostics.length)$('diagnostics').textContent='No findings under this browser policy.';for(const d of result.diagnostics){const button=document.createElement('button');button.className='diagnostic';const title=document.createElement('strong');title.textContent=`${d.severity} · ${d.code} · line ${d.span.line}${d.code.startsWith('MATH-')?' (line only)':`, column ${d.span.col}`}`;button.append(title,document.createTextNode(d.message));button.onclick=()=>{const lines=$('source').value.split('\n');const offset=lines.slice(0,d.span.line-1).reduce((n,line)=>n+line.length+1,0);$('source').focus();$('source').setSelectionRange(offset,offset+(lines[d.span.line-1]?.length||0));};button.title='Select this source line';$('diagnostics').append(button);}$('held').replaceChildren(...result.unassessed.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));if(previewURL)retiredURLs.add(previewURL);previewURL=URL.createObjectURL(new Blob([result.html],{type:'text/html'}));$('preview').onload=()=>{for(const url of retiredURLs)URL.revokeObjectURL(url);retiredURLs.clear();};$('preview').src=previewURL;$('preview').hidden=$('view').value!=='html';$('terminal').textContent=result.terminal;};
$('source').addEventListener('input',check);$('load').onclick=()=>{$('source').value=examples[$('example').value];history.replaceState(null,'',location.pathname+'?example='+$('example').value);check();};$('view').onchange=()=>{$('preview').hidden=!result||$('view').value!=='html';$('terminal').hidden=$('view').value!=='terminal';};
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('markdown').onclick=()=>result&&download(result.source,'document.md','text/markdown');$('html').onclick=()=>result&&download(result.html,'document.html','text/html');$('json').onclick=()=>result&&download(JSON.stringify(result,null,2),'proof-report.json','application/json');
$('share').onclick=()=>{if(new TextEncoder().encode($('source').value).length>8192){$('status').textContent='Sharing is limited to 8 KB. Download larger sources instead.';return;}history.replaceState(null,'',location.pathname+'#source='+encodeURIComponent($('source').value));$('status').textContent='Source is in this URL. Copy the address to share it.';};
const key=new URLSearchParams(location.search).get('example');$('example').value=Object.hasOwn(examples,key)?key:'guide';$('source').value=examples[$('example').value];try{if(location.hash.startsWith('#source=')&&location.hash.length<26000)$('source').value=decodeURIComponent(location.hash.slice(8));}catch{$('status').textContent='Invalid shared source; loaded Field notes.';}
